// supabase/functions/telegram-webhook/index.ts
// Sanya Messenger
// Telegram Stars payment webhook
//
// Handles:
// - pre_checkout_query
// - successful_payment
//
// IMPORTANT:
// - No mock payment
// - No hardcoded admin ID
// - No in-memory database
// - Premium = 99 XTR / 30 days
// - Subscription is activated ONLY after successful_payment

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

/* =========================================================
   ENVIRONMENT
   ========================================================= */

const TOKEN = Deno.env.get("TELEGRAM_BOT_TOKEN") ?? "";

const ADMIN_ID = Number(
  Deno.env.get("TELEGRAM_ADMIN_ID") ?? "0",
);

const WEBHOOK_SECRET =
  Deno.env.get("TELEGRAM_WEBHOOK_SECRET") ?? "";

const SUPABASE_URL =
  Deno.env.get("https://emqseukhovnzgrmsvlag.supabase.co") ?? "";

const SERVICE_ROLE_KEY =
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

const PREMIUM_AMOUNT = 99;
const PREMIUM_DAYS = 30;
const PREMIUM_SECONDS =
  PREMIUM_DAYS * 24 * 60 * 60;

/* =========================================================
   SUPABASE
   ========================================================= */

const db = createClient(
  SUPABASE_URL,
  SERVICE_ROLE_KEY,
);

/* =========================================================
   TELEGRAM API
   ========================================================= */

async function telegram(
  method: string,
  body: unknown,
) {
  if (!TOKEN) {
    throw new Error(
      "TELEGRAM_BOT_TOKEN is not configured",
    );
  }

  const response = await fetch(
    `https://api.telegram.org/bot${TOKEN}/${method}`,
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
      },
      body: JSON.stringify(body),
    },
  );

  let data: any;

  try {
    data = await response.json();
  } catch {
    throw new Error(
      `Telegram API returned invalid JSON (${response.status})`,
    );
  }

  if (!response.ok || !data?.ok) {
    throw new Error(
      data?.description ??
        `Telegram API error (${response.status})`,
    );
  }

  return data.result;
}

/* =========================================================
   RESPONSE HELPERS
   ========================================================= */

function response(
  data: unknown,
  status = 200,
) {
  return new Response(
    JSON.stringify(data),
    {
      status,
      headers: {
        "content-type":
          "application/json; charset=utf-8",
      },
    },
  );
}

/* =========================================================
   PAYMENT PAYLOAD VALIDATION
   =========================================================
   
   Invoice payload generated by /create-invoice:

   premium_<telegramUserId>_<timestamp>

   Example:

   premium_123456789_1760000000000
*/

function parsePremiumPayload(
  payload: unknown,
): {
  valid: boolean;
  userId: number | null;
} {
  if (
    typeof payload !== "string" ||
    !payload
  ) {
    return {
      valid: false,
      userId: null,
    };
  }

  const match =
    /^premium_(\d+)_(\d+)$/.exec(
      payload,
    );

  if (!match) {
    return {
      valid: false,
      userId: null,
    };
  }

  const userId = Number(match[1]);

  if (
    !Number.isSafeInteger(userId) ||
    userId <= 0
  ) {
    return {
      valid: false,
      userId: null,
    };
  }

  return {
    valid: true,
    userId,
  };
}

/* =========================================================
   BAN CHECK
   ========================================================= */

async function isUserBanned(
  userId: number,
): Promise<boolean> {
  const {
    data,
    error,
  } = await db
    .from("profiles")
    .select("is_banned")
    .eq("user_id", userId)
    .maybeSingle();

  if (error) {
    console.error(
      "Ban check failed:",
      error.message,
    );

    throw new Error(
      "Unable to verify account status",
    );
  }

  return Boolean(
    data?.is_banned,
  );
}

/* =========================================================
   SUCCESSFUL PAYMENT HANDLER
   ========================================================= */

async function handleSuccessfulPayment(
  update: any,
) {
  const payment =
    update?.message?.successful_payment;

  const telegramUser =
    update?.message?.from;

  if (!payment) {
    throw new Error(
      "successful_payment object missing",
    );
  }

  if (
    !telegramUser ||
    !telegramUser.id
  ) {
    throw new Error(
      "Telegram payment user missing",
    );
  }

  const userId = Number(
    telegramUser.id,
  );

  if (
    !Number.isSafeInteger(userId) ||
    userId <= 0
  ) {
    throw new Error(
      "Invalid Telegram user ID",
    );
  }

  /* -------------------------------------------------------
     1. Validate currency
     ------------------------------------------------------- */

  const currency =
    String(
      payment.currency ?? "",
    );

  if (currency !== "XTR") {
    throw new Error(
      `Invalid payment currency: ${currency}`,
    );
  }

  /* -------------------------------------------------------
     2. Validate amount
     ------------------------------------------------------- */

  const amount = Number(
    payment.total_amount,
  );

  if (
    !Number.isSafeInteger(amount) ||
    amount !== PREMIUM_AMOUNT
  ) {
    throw new Error(
      `Invalid payment amount: expected ${PREMIUM_AMOUNT} XTR, received ${amount}`,
    );
  }

  /* -------------------------------------------------------
     3. Validate charge ID
     ------------------------------------------------------- */

  const chargeId =
    String(
      payment.telegram_payment_charge_id ??
        "",
    );

  if (!chargeId) {
    throw new Error(
      "Telegram payment charge ID missing",
    );
  }

  /* -------------------------------------------------------
     4. Validate invoice payload
     ------------------------------------------------------- */

  const payload =
    String(
      payment.invoice_payload ?? "",
    );

  const parsedPayload =
    parsePremiumPayload(
      payload,
    );

  if (
    !parsedPayload.valid ||
    parsedPayload.userId === null
  ) {
    throw new Error(
      "Invalid Premium invoice payload",
    );
  }

  if (
    parsedPayload.userId !== userId
  ) {
    throw new Error(
      "Payment user does not match invoice user",
    );
  }

  /* -------------------------------------------------------
     5. Admin must never need Premium
     ------------------------------------------------------- */

  if (
    ADMIN_ID > 0 &&
    userId === ADMIN_ID
  ) {
    console.warn(
      "Admin payment received. Admin does not require Premium.",
    );

    /*
     * We do not activate a paid subscription
     * for the admin.
     */
  }

  /* -------------------------------------------------------
     6. Check banned status
     ------------------------------------------------------- */

  const banned =
    await isUserBanned(
      userId,
    );

  if (banned) {
    throw new Error(
      "Banned account attempted Premium payment",
    );
  }

  /* -------------------------------------------------------
     7. Ensure profile exists
     ------------------------------------------------------- */

  const {
    error: profileError,
  } = await db
    .from("profiles")
    .upsert(
      {
        user_id: userId,
        username:
          telegramUser.username ??
          null,
        first_name:
          telegramUser.first_name ??
          null,
        last_name:
          telegramUser.last_name ??
          null,
        updated_at:
          new Date().toISOString(),
      },
      {
        onConflict: "user_id",
      },
    );

  if (profileError) {
    console.error(
      "Profile upsert failed:",
      profileError.message,
    );

    throw new Error(
      `Profile update failed: ${profileError.message}`,
    );
  }

  /* -------------------------------------------------------
     8. Idempotency check
     ------------------------------------------------------- */

  const {
    data: existingPayment,
    error: existingPaymentError,
  } = await db
    .from("payments")
    .select(
      "id, user_id, amount, currency, telegram_payment_charge_id",
    )
    .eq(
      "telegram_payment_charge_id",
      chargeId,
    )
    .maybeSingle();

  if (existingPaymentError) {
    console.error(
      "Payment lookup failed:",
      existingPaymentError.message,
    );

    throw new Error(
      `Payment lookup failed: ${existingPaymentError.message}`,
    );
  }

  const isNewPayment =
    !existingPayment;

  /* -------------------------------------------------------
     9. Insert payment only once
     ------------------------------------------------------- */

  if (isNewPayment) {
    const {
      error: paymentInsertError,
    } = await db
      .from("payments")
      .insert({
        user_id: userId,
        amount: amount,
        currency: currency,
        telegram_payment_charge_id:
          chargeId,
        invoice_payload:
          payload,
      });

    if (paymentInsertError) {
      console.error(
        "Payment insert failed:",
        paymentInsertError.message,
      );

      throw new Error(
        `Payment insert failed: ${paymentInsertError.message}`,
      );
    }
  } else {
    /*
     * Telegram may retry the same update.
     *
     * The payment already exists, so do not
     * insert another payment.
     */
    console.log(
      `Payment ${chargeId} already processed.`,
    );
  }

  /* -------------------------------------------------------
     10. Activate 30-day Premium
     ------------------------------------------------------- */

  /*
   * IMPORTANT:
   *
   * We intentionally use only confirmed
   * subscription columns.
   *
   * No "total_paid" column is assumed.
   */

  const start =
    new Date();

  const end =
    new Date(
      start.getTime() +
        PREMIUM_SECONDS * 1000,
    );

  const {
    error: subscriptionError,
  } = await db
    .from("subscriptions")
    .upsert(
      {
        user_id: userId,
        subscription_start:
          start.toISOString(),
        subscription_end:
          end.toISOString(),
        lifetime: false,
        is_active: true,
        updated_at:
          start.toISOString(),
      },
      {
        onConflict: "user_id",
      },
    );

  if (subscriptionError) {
    console.error(
      "Subscription activation failed:",
      subscriptionError.message,
    );

    throw new Error(
      `Subscription activation failed: ${subscriptionError.message}`,
    );
  }

  console.log(
    `Premium activated for ${userId} until ${end.toISOString()}`,
  );

  /* -------------------------------------------------------
     11. Notify user only for a new payment
     ------------------------------------------------------- */

  if (isNewPayment) {
    try {
      await telegram(
        "sendMessage",
        {
          chat_id: userId,
          text:
            "✨ Premium activated for 30 days!\n\n" +
            "You can now use private messaging with Sanya.",
        },
      );
    } catch (error) {
      /*
       * Payment and subscription are already
       * successfully stored.
       *
       * Notification failure must not undo them.
       */
      console.error(
        "User notification failed:",
        error instanceof Error
          ? error.message
          : String(error),
      );
    }
  }

  /* -------------------------------------------------------
     12. Notify admin for a new payment
     ------------------------------------------------------- */

  if (
    isNewPayment &&
    ADMIN_ID > 0
  ) {
    try {
      const name =
        telegramUser.first_name ??
        "User";

      const username =
        telegramUser.username
          ? `@${telegramUser.username}`
          : "No username";

      await telegram(
        "sendMessage",
        {
          chat_id: ADMIN_ID,
          text:
            "💳 New Premium Payment\n\n" +
            `User: ${name}\n` +
            `Username: ${username}\n` +
            `Telegram ID: ${userId}\n` +
            `Amount: ${amount} XTR ⭐\n` +
            "Plan: Premium — 30 Days",
        },
      );
    } catch (error) {
      console.error(
        "Admin notification failed:",
        error instanceof Error
          ? error.message
          : String(error),
      );
    }
  }

  return {
    ok: true,
    user_id: userId,
    new_payment: isNewPayment,
    premium_active: true,
    subscription_end:
      end.toISOString(),
  };
}

/* =========================================================
   PRE-CHECKOUT HANDLER
   ========================================================= */

async function handlePreCheckout(
  update: any,
) {
  const pc =
    update?.pre_checkout_query;

  if (!pc) {
    throw new Error(
      "pre_checkout_query missing",
    );
  }

  const queryId =
    String(pc.id ?? "");

  const userId =
    Number(
      pc.from?.id,
    );

  if (!queryId) {
    throw new Error(
      "pre_checkout_query ID missing",
    );
  }

  if (
    !Number.isSafeInteger(userId) ||
    userId <= 0
  ) {
    await telegram(
      "answerPreCheckoutQuery",
      {
        pre_checkout_query_id:
          queryId,
        ok: false,
        error_message:
          "Invalid Telegram account.",
      },
    );

    return {
      ok: false,
    };
  }

  /* -------------------------------------------------------
     Validate amount
     ------------------------------------------------------- */

  const amount =
    Number(
      pc.total_amount,
    );

  if (
    !Number.isSafeInteger(amount) ||
    amount !== PREMIUM_AMOUNT
  ) {
    await telegram(
      "answerPreCheckoutQuery",
      {
        pre_checkout_query_id:
          queryId,
        ok: false,
        error_message:
          "Invalid Premium price.",
      },
    );

    return {
      ok: false,
    };
  }

  /* -------------------------------------------------------
     Validate currency
     ------------------------------------------------------- */

  const currency =
    String(
      pc.currency ?? "",
    );

  if (currency !== "XTR") {
    await telegram(
      "answerPreCheckoutQuery",
      {
        pre_checkout_query_id:
          queryId,
        ok: false,
        error_message:
          "Invalid payment currency.",
      },
    );

    return {
      ok: false,
    };
  }

  /* -------------------------------------------------------
     Validate payload
     ------------------------------------------------------- */

  const payload =
    String(
      pc.invoice_payload ?? "",
    );

  const parsedPayload =
    parsePremiumPayload(
      payload,
    );

  if (
    !parsedPayload.valid ||
    parsedPayload.userId === null
  ) {
    await telegram(
      "answerPreCheckoutQuery",
      {
        pre_checkout_query_id:
          queryId,
        ok: false,
        error_message:
          "Invalid Premium invoice.",
      },
    );

    return {
      ok: false,
    };
  }

  if (
    parsedPayload.userId !== userId
  ) {
    await telegram(
      "answerPreCheckoutQuery",
      {
        pre_checkout_query_id:
          queryId,
        ok: false,
        error_message:
          "Payment account mismatch.",
      },
    );

    return {
      ok: false,
    };
  }

  /* -------------------------------------------------------
     Ban check
     ------------------------------------------------------- */

  const banned =
    await isUserBanned(
      userId,
    );

  if (banned) {
    await telegram(
      "answerPreCheckoutQuery",
      {
        pre_checkout_query_id:
          queryId,
        ok: false,
        error_message:
          "Your account is suspended.",
      },
    );

    return {
      ok: false,
    };
  }

  /* -------------------------------------------------------
     Admin does not need Premium
     ------------------------------------------------------- */

  if (
    ADMIN_ID > 0 &&
    userId === ADMIN_ID
  ) {
    await telegram(
      "answerPreCheckoutQuery",
      {
        pre_checkout_query_id:
          queryId,
        ok: false,
        error_message:
          "Admin account does not require Premium.",
      },
    );

    return {
      ok: false,
    };
  }

  /* -------------------------------------------------------
     APPROVE CHECKOUT
     ------------------------------------------------------- */

  await telegram(
    "answerPreCheckoutQuery",
    {
      pre_checkout_query_id:
        queryId,
      ok: true,
    },
  );

  console.log(
    `Pre-checkout approved for user ${userId}`,
  );

  return {
    ok: true,
  };
}

/* =========================================================
   MAIN WEBHOOK
   ========================================================= */

Deno.serve(
  async (req: Request) => {
    /* -------------------------------------------------------
       OPTIONS
       ------------------------------------------------------- */

    if (
      req.method === "OPTIONS"
    ) {
      return response({
        ok: true,
      });
    }

    /* -------------------------------------------------------
       Only POST is accepted
       ------------------------------------------------------- */

    if (
      req.method !== "POST"
    ) {
      return response(
        {
          ok: false,
          error:
            "Method not allowed",
        },
        405,
      );
    }

    /* -------------------------------------------------------
       Verify Telegram webhook secret
       ------------------------------------------------------- */

    if (WEBHOOK_SECRET) {
      const receivedSecret =
        req.headers.get(
          "x-telegram-bot-api-secret-token",
        );

      if (
        receivedSecret !==
        WEBHOOK_SECRET
      ) {
        console.error(
          "Invalid Telegram webhook secret.",
        );

        return response(
          {
            ok: false,
            error:
              "Unauthorized",
          },
          401,
        );
      }
    }

    /* -------------------------------------------------------
       Parse update
       ------------------------------------------------------- */

    let update: any;

    try {
      update =
        await req.json();
    } catch {
      return response(
        {
          ok: false,
          error:
            "Invalid JSON",
        },
        400,
      );
    }

    try {
      /* -----------------------------------------------------
         PRE-CHECKOUT
         ----------------------------------------------------- */

      if (
        update?.pre_checkout_query
      ) {
        const result =
          await handlePreCheckout(
            update,
          );

        return response(
          result,
        );
      }

      /* -----------------------------------------------------
         SUCCESSFUL PAYMENT
         ----------------------------------------------------- */

      if (
        update?.message
          ?.successful_payment
      ) {
        const result =
          await handleSuccessfulPayment(
            update,
          );

        return response(
          result,
        );
      }

      /*
       * Other Telegram updates are harmless.
       */
      return response({
        ok: true,
        ignored: true,
      });
    } catch (error) {
      console.error(
        "Telegram webhook processing error:",
        error instanceof Error
          ? error.stack ||
            error.message
          : String(error),
      );

      /*
       * Return 500 so Telegram can retry
       * important payment updates.
       *
       * Payment processing is idempotent,
       * so retries are safe.
       */

      return response(
        {
          ok: false,
          error:
            error instanceof Error
              ? error.message
              : "Webhook processing failed",
        },
        500,
      );
    }
  },
);
